---
    version: "2.1"
    services:
      wireguard:
        image: linuxserver/wireguard:latest
        container_name: wireguard
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
          - SERVERURL=<public ip or domain> #optional
          - SERVERPORT=<port-freely chosen 51820> #optional
          - PEERS=1
          - PEERS=2
          - PEERS=3
          - PEERDNS=auto #optional
          - INTERNAL_SUBNET=10.13.13.0 #optional
        volumes:
          - ./config:/config
          - /lib/modules:/lib/modules
        ports:
          - 51820:51820/udp
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped